apiVersion: v1
kind: Service
metadata:
  name: techvault-service
  namespace: techvault
  labels:
    app: techvault
spec:
  type: NodePort
  selector:
    app: techvault
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
    name: http
